logging.level:
  org.springframework.data.jpa: DEBUG
  org.springframework.test.context.jdbc: DEBUG
  com.vmware.tanzulabs.patterns.person: DEBUG

spring:

  application:
    name: liquibase-demo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  h2:
    console.enabled: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: ALWAYS
